### ISSUE TITLE
implement qa automations api repository template

### ISSUE THREAD

**Issue by Kravalg** [VilnaCRM-Org/tests-template#1]
As a developer, I need to be able easily to create and set up new repository to write API auto tests.

### Technical requirements

- [x] Python 3
- [x] PyTest
- [x] [Requests](https://github.com/psf/requests)
- [x] [Behave](https://behave.readthedocs.io/en/stable/index.html)
- [x] [allure-python](https://github.com/allure-framework/allure-python)
- [x] [graphene](https://github.com/graphql-python/graphene)

### Tasks

- [x] create the repository template
- [x] set up docker
- [x] set up CI checks using Github actions ([conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), [pylint](https://github.com/pylint-dev/pylint), pytest, behave, [bandit](https://github.com/PyCQA/bandit), snyk)
- [x] configure conventional commits git hook
- [x] add make command as for [php-service-template](https://github.com/VilnaCRM-Org/php-service-template/blob/main/Makefile) to work with project
- [x] write for all repositories CONTRIBUTE.md, README.md, SECURITY.md
- [x] add [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

### CI checks for Github

- [x] GitHub actions CI
- [x] Snyk
- [x] CodeScene
- [x] [docker-bench-security](https://github.com/docker/docker-bench-security)
- [x] [Github Secret scanning](https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning)

### Acceptance criteria

- [x] the QA Automations template implemented and works as GitHub public template
- [x] all tests passed
